[package]
name = "hashira-axum"
description = "Axum adapter for hashira"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.15"
futures = "0.3.28"
hashira = { path = "../hashira" }
hyper = { version = "0.14.26", features = ["stream"] }
tower-http = { version = "0.4.0", features = ["fs"] }
tower = "0.4.13"