[template]
cargo_generate_version = ">=0.10.0"
include = ["./templates"]
sub_templates = [
    "./templates/with-actix-web",
    "./templates/with-axum",
    "./templates/with-rocket",
    "./templates/with-deno",
    "./examples/*"
]
