[workspace]
members = ["packages/*", "adapters/*", "examples/*", "tests/*"]
default-members = ["packages/*"]
exclude = ["templates"]
resolver = "2"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = "z"
