[env]
BUILD_CMD = "build"

[env.prod]
BUILD_CMD = "build --release"

[tasks.deno-run.env]
HASHIRA_WASM_LIB = "{{crate_name}}"
HASHIRA_STATIC_DIR = "static/"
HASHIRA_HOST = "127.0.0.1"
HASHIRA_PORT = 5000

# Build wasm server
[tasks.cargo-build]
command = "cargo"
args = ["@@split(BUILD_CMD, )", "--target", "wasm32-unknown-unknown"]

[tasks.wasm-bindgen]
command = "wasm-bindgen"
args = [
    "target/wasm32-unknown-unknown/debug/{{crate_name}}.wasm",
    "--target",
    "deno",
    "--out-dir",
    "build/",
    "--out-name",
    "{{crate_name}}_server"
]

[tasks.build-wasm]
dependencies = ["cargo-build", "wasm-bindgen"]

# Build wasm client
[tasks.cargo-build-client]
command = "cargo"
args = ["@@split(BUILD_CMD, )", "--target", "wasm32-unknown-unknown", "--features", "client"]

[tasks.wasm-bindgen-client]
command = "wasm-bindgen"
args = [
    "target/wasm32-unknown-unknown/debug/{{crate_name}}.wasm",
    "--target",
    "web",
    "--out-dir",
    "public/",
    "--no-typescript",
]

[tasks.build-wasm-client]
dependencies = ["cargo-build-client", "wasm-bindgen-client"]

[tasks.build]
dependencies = ["build-wasm", "build-wasm-client"]

# Start deno server
[tasks.deno-run]
command = "deno"
args = ["run", "--allow-read", "--allow-net", "--allow-env", "src/index.ts"]

[tasks.run]
dependencies = ["build", "deno-run"]
