[config]
default_to_workspace = false

[env]
TARGET_DIR = "../../target"

[tasks.build_client]
command = "cargo"
args = ["build", "--target", "wasm32-unknown-unknown"]

[tasks.build_wasm]
script = "wasm-bindgen --target web --no-typescript --out-dir ../../target/debug/public ../../target/wasm32-unknown-unknown/debug/actix_web_sample_web.wasm"

[tasks.copy_public_dir]
script_runner = "@shell"
script = "cp public/* ../../target/debug/public"

[tasks.cleanup]
script_runner = "@shell"
script = "rm index.html"

[tasks.build]
dependencies = [
    "build_client",
    "build_wasm",
    "copy_public_dir",
    "cleanup",
]
