[config]
default_to_workspace = false

[tasks.build_html]
command = "cargo"
args = ["run", "--features", "build"]

[tasks.build_client]
command = "trunk"
args = [
    "build",
    "--dist",
    "../../target/debug/public",
    "--public-url",
    "static/",
    "--filehash=false",
]

[tasks.copy_public_dir]
script_runner = "@shell"
script = "cp public/* ../../target/debug/public"

[tasks.cleanup]
script_runner = "@shell"
script = "rm index.html"

[tasks.build]
dependencies = ["build_html", "build_client", "copy_public_dir", "cleanup"]
