[package]
name = "hashira"
description = "A server side rendering framework build on top of Yew"
version = "0.0.1"
edition = "2021"
repository = "https://github.com/Neo-Ciber94/hashira"
license = "MIT"

[dependencies]
yew = { version = "0.20.0", features = ["ssr", "hydration"] }
cookie = { version = "0.17.0", features = ["percent-encode"] }
web-sys = "0.3.61"
route-recognizer = "0.3.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
http = "0.2.9"
bytes = "1.4.0"
log = "0.4.17"
