[package]
name = "hashira"
description = "A server side rendering framework build on top of Yew"
version = "0.0.1"
edition = "2021"
repository = "https://github.com/Neo-Ciber94/hashira"
license = "MIT"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
lol_html = "0.3.3"

[dependencies]
yew = { version = "0.20.0", features = ["ssr", "hydration"] }
hashira-macros = { path = "../hashira-macros" }
cookie = { version = "0.17.0", features = ["percent-encode"] }
web-sys = "0.3.61"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
http = "0.2.9"
bytes = "1.4.0"
log = "0.4.17"
indexmap = "1.9.3"
once_cell = "1.17.1"
serde_qs = "0.12.0"
thiserror = "1.0.40"
async-trait = { version = "0.1.68", optional = true }
matchit = "0.7.0"
futures = "0.3.28"
tokio-stream = { version = "0.1.12", features = ["sync"] }
tokio = { version = "1.27.0", features = ["sync"] }

[features]
hooks = ["async-trait"]
