[package]
name = "hashira"
description = "A server side rendering framework build on top of Yew"
version = "0.0.1-alpha"
edition = "2021"
repository = "https://github.com/Neo-Ciber94/hashira"
authors = ["Freddy L. Paredes (neo-ciber_94@hotmail.com)"]
license = "MIT"
keywords = ["web", "web-framework", "server-side-rendering", "yew"]
readme = "../../README.md"

[dependencies]
yew = { version = "0.20.0", features = ["ssr", "hydration"] }
hashira-macros = { path = "../hashira-macros", version = "0.0.1-alpha" }
cookie = { version = "0.17.0", features = ["percent-encode"] }
web-sys = "0.3.61"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
http = "0.2.9"
bytes = "1.4.0"
log = "0.4.17"
indexmap = { version = "1.9.3", features = ["serde"] }
once_cell = "1.17.1"
serde_qs = "0.12.0"
thiserror = "1.0.40"
async-trait = { version = "0.1.68" }
matchit = "0.7.0"
futures = { version = "0.3.28", features = ["executor"] }
tokio-stream = { version = "0.1.14", features = ["sync"] }
tokio = { version = "1.28.0", features = ["sync"] }
mime = "0.3.17"
serde_urlencoded = "0.7.1"
pin-project-lite = "0.2.9"
console_error_panic_hook = "0.1.7"

[target.'cfg(target_arch = "wasm32")'.dependencies]
# We use this dependencies to safely render the html layout on wasm without blocking
prokio = "0.1.0"
fragile = "2.0.0"

[features]
# Enable hooks to the hashira steps
hooks = []

# Tells hashira is running on a client side
client = []

[dev-dependencies]
tokio = { version = "1.28.0", features = ["macros", "rt"] }
