[package]
name = "hashira-cli"
description = "A command line utility for building hashira applications"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "hashira"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.70"
axum = { version = "0.6.12", features = ["ws"] }
cargo_metadata = "0.15.3"
cargo_toml = "0.15.2"
clap = { version = "4.2.1", features = ["derive"] }
futures = "0.3.28"
glob = "0.3.1"
notify = { version = "5.1.0" }
tokio-stream = { version = "0.1.12", features = ["sync"] }
tokio = { version = "1.27.0", features = [
    "fs",
    "io-util",
    "macros",
    "process",
    "signal",
    "sync",
    "rt-multi-thread",
] }
notify-debouncer-mini = "0.2.1"
serde_json = "1.0.95"
serde = { version = "1.0.159", features = ["derive"] }
once_cell = "1.17.1"
wasm-opt = "0.112.0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
async-trait = "0.1.68"
cap-directories = "1.0.14"
reqwest = { version = "0.11.16", features = ["stream"]}
cap-std = "1.0.14"
thiserror = "1.0.40"
tempfile = "3.5.0"
flate2 = "1.0.25"
tar = "0.4.38"
zip = "0.6.4"
which = "4.4.0"

[dev-dependencies]
tokio = { version = "1.27.0", features = ["macros", "rt"] }
