[package]
name = "hashira-cli"
description = "A command line utility for building hashira applications"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
cargo_metadata = "0.15.3"
cargo_toml = "0.15.2"
clap = { version = "4.2.1", features = ["derive"] }
env_logger = "0.10.0"
futures = "0.3.28"
glob = "0.3.1"
log = "0.4.17"
tokio = { version = "1.27.0", features = [
    "fs",
    "io-util",
    "macros",
    "process",
    "rt-multi-thread",
] }
