[package]
name = "hashira-cli"
description = "A command line utility for building hashira applications"
repository = "https://github.com/Neo-Ciber94/hashira"
version = "0.0.1-alpha"
edition = "2021"
keywords = ["cli", "web", "web-framework", "ssr", "yew"]
license = "MIT"
readme = "README.md"

[[bin]]
name = "hashira"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.71"
axum = { version = "0.6.18", features = ["ws"] }
cargo_metadata = "0.15.4"
cargo_toml = "0.15.2"
clap = { version = "4.2.5", features = ["derive"] }
futures = "0.3.28"
glob = "0.3.1"
notify = { version = "5.1.0" }
tokio-stream = { version = "0.1.14", features = ["sync"] }
tokio = { version = "1.28.0", features = [
    "fs",
    "io-util",
    "macros",
    "process",
    "signal",
    "sync",
    "rt-multi-thread",
    "parking_lot"
] }
notify-debouncer-mini = "0.2.1"
serde_json = "1.0.96"
serde = { version = "1.0.160", features = ["derive"] }
once_cell = "1.17.1"
wasm-opt = "0.112.0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
async-trait = "0.1.68"
reqwest = { version = "0.11.17", features = ["stream", "json"]}
thiserror = "1.0.40"
tempfile = "3.5.0"
flate2 = "1.0.26"
tar = "0.4.38"
zip = "0.6.4"
which = "4.4.0"
dunce = "1.0.4"
lightningcss = "1.0.0-alpha.41"
directories = "5.0.1"
enum-iterator = "1.4.0"
dialoguer = "0.10.4"
console = "0.15.5"
octocrab = "0.22.0"

[dev-dependencies]
tokio = { version = "1.28.0", features = ["macros", "rt", "rt-multi-thread"] }
