[package]
name = "hashira-actix-web"
description = "Actix-web adapter for hashira"
version = "0.1.0"
edition = "2021"

[dependencies]
hashira = { path = "../hashira" }
actix-web = "4.3.1"
futures = "0.3.28"
actix-files = "0.6.2"