[package]
name = "hashira-macros"
version = "0.0.1-alpha"
repository = "https://github.com/Neo-Ciber94/hashira"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = "2.0.15"
proc-macro2 = "1.0.56"