name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Build project
      - name: Build
        run: cargo build --verbose

      # Run clippy
      - name: Run clippy
        run: cargo clippy

  # Run tests
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os}}
    name: Test | ${{ matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run Test (${{ matrix.os}})
        run: cargo test --verbose
