name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - run: cargo build --verbose
      - run: cargo build --features client --verbose
      - run: cargo clippy -- -D warnings

  # Run tests
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os}}
    name: Test | ${{ matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - run: cargo test --verbose
      - run: cargo test --features client --verbose
